name: Deploy to Vercel2

on:
  # push:
  # workflow_dispatch:
  schedule:
  # CRON JOB TIJDEN : Minuut Uur DagVanDeMaand(1 - 31) Maand(1 - 12) DagVanDeWeek(0 - 6)
  # elke dag om 16.00 uur UTC (Universal Time, in NL 17.00 of 18.00 uur.)
    - cron: "0 16 * * *"
  
  # Elke dag om 12 UTC
  #  - cron: "0 12 * * *"

  # Elke maandag om 13.00 uur UTC
  #  - cron: "0 13 * * 1"

  # Elke eerste dag van de maand
  #  - cron: "0 0 1 * *"

  # Elke werkdag om 15.15 UTC 
  #  - cron: "15 15 * * 1-5"



jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout results
        uses: actions/checkout@v2
        with:
          ref: refs/heads/results
          path: results
      - name: Checkout speedlify
        uses: actions/checkout@v2
        with:
          path: default
      - name: Copy existing results
        run: cp -r results/. default/_data
      - run: |
          mkdir .vercel
          echo $VERCEL_PROJECT > .vercel/project.json
          npx vercel --prod --token $VERCEL_TOKEN
        working-directory: default
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT: ${{ secrets.VERCEL_PROJECT }}
